### ISSUE TITLE
Define purpose and scope of projects

### ISSUE THREAD

**Issue by EvanLovely** [drupal-pattern-lab/roadmap#1]
@aleksip [Originally](https://github.com/drupal-pattern-lab/drupal-pattern-lab.github.io/issues/10) wrote:

> Is everything under this GitHub organization going to be tightly focused on Pattern Lab related things only?
I think it might often be hard to make a distinction between the more general 'component based theming in Drupal' best practices etc. and Pattern Lab specific ones. If we want to be Pattern Lab specific, where is the home for the more general stuff?
If we want to go for a more general approach, then maybe we could still change the name of the organization to something more general at this point? "There are only two hard things in Computer Science" so of course I don't have a suggestion for a good name. :)

**Comment by EvanLovely** [comment]
I like the current name as it creates a tightly defined scope: we are dedicated to getting Pattern Lab working in Drupal. I *totally* agree that many of the concepts and solutions have application outside those two projects overlapping focus, but I think that the focus would be good for the working group as it limits it to making those two projects work. I also agree that it could be limiting to ourselves down the line, but I don't know if it warrants making any overly vague name like something that would use Components. Additionally, we'd have some good SEO for those searching "drupal pattern lab"!

Final thoughts? We can still change the name, but we are getting VERY close to a point where we can't turn back. Looking for sign off from @aleksip @evanmwillhite and @sghoweri

**Comment by cybtachyon** [comment]
To me,

>'component based theming in Drupal' best practices etc.

Is a bit of a hard concept to wrangle at this point in time - just doing a google search (or reading the Drupalcon BoF notes) reveals hundreds of different implementations using varying technologies.

I personally have worked with 3 separate Drupal 8 implementations for productions sites within the past two years and they all have their pros and cons - no clear preferred technology is sitting on top, although Pattern Lab assuredly has the most features and use cases.

IMHO Creating an easier Drupal + Pattern Lab integration & improvement on Pattern Lab's Twig variant (that's not just a Drupal 8 theme starter kit) will go along way towards filling in the gaps with one of the most powerful and complete tools currently used in Drupal Component-Driven Development.

**Comment by evanmwillhite** [comment]
Yep, I agree on the PL/Drupal focus. I think we will likely impact the wider conversation of component-based theming as well, but there is enough of a need just around the tooling of this specific integration that we will do better to focus on that.

**Comment by sghoweri** [comment]
I'm not a huge fan of the name from a marketing perspective (I'd prefer something more along the lines of the "Pattern Lab - Drupal Alliance" BUT I think it's practical and very much about what the group's core focus is about -- bridging the gaps in component-driven development using Pattern Lab and Drupal 8 + providing consolidated resources on where this whole industry shift is heading + what's worked for a lot of us. 

I'd recommend we stick with the name / focus for now so we can start moving forward with our laundry list of things to tackle.

And for what it's worth, if / when we hit a point where what we've built or what we're focusing on needs to be more inclusive or more general (or if we do such a great job that this thing is no longer needed at some point), we can most definitely look into a rebrand / branching out to cover more component-driven work going on.

**Comment by EvanLovely** [comment]
OK, we've got the **machine name** of our group: `drupal-pattern-lab` - we can always change the human readable name to something else later; but our GitHub org & repo urls are locked to this now. Closing this discussion out!
